# Importing Libraries And Loading NLP(Binary Text Classification) Dataset From Kaggle.com

In [204]:
import numpy as np
import pandas as pd
df = pd.read_csv("tweets.csv")
df.info()
df

C:\Users\User\AppData\Local\Temp\ipykernel_13032\1389259119.py:3: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("tweets.csv")


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 478052 entries, 0 to 478051
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype  
---  ------           --------------   -----  
 0   date             478052 non-null  object 
 1   content          478052 non-null  object 
 2   hashtags         478034 non-null  object 
 3   like_count       478035 non-null  float64
 4   rt_count         478035 non-null  float64
 5   followers_count  478035 non-null  float64
 6   isVerified       478035 non-null  object 
 7   language         478035 non-null  object 
 8   coordinates      20669 non-null   object 
 9   place            20196 non-null   object 
 10  source           478035 non-null  object 
dtypes: float64(3), object(8)
memory usage: 40.1+ MB


date  \
0       2023-02-21 03:30:04+00:00   
1       2023-02-21 03:29:07+00:00   
2       2023-02-21 03:29:04+00:00   
3       2023-02-21 03:28:06+00:00   
4       2023-02-21 03:27:38+00:00   
...                           ...   
478047  2023-02-06 00:04:00+00:00   
478048  2023-02-06 00:03:53+00:00   
478049  2023-02-06 00:01:25+00:00   
478050  2023-02-06 00:01:03+00:00   
478051  2023-02-06 00:00:00+00:00   

                                                  content  \
0       तुर्की में सोमवार देर रात भूंकप के तेज झटके मह...   
1       New search &amp; rescue work is in progress in...   
2       Can't imagine those who still haven't recovere...   
3       its a highkey sign for all of us to ponder ove...   
4       Turkiye Earthquake: तुर्किए में फिर आया भूकंप ...   
...                                                   ...   
478047  Author Birol Bahadir is very busy these days g...   
478048  #Earthquake (#terremoto) M2.5 strikes 125 km W...   
478049  #Earthquake (#sismo) M2.8 strikes 72 km NE of ...   
478050  From Istanbul to New York – Discovering The La...   
478051  🔹The arrest cases documented were of 25 young ...   

                                                 hashtags  like_count  \
0       ['ATDigital', 'Turkey', 'Earthquake', 'TurkeyE...         0.0   
1       ['Hatay', 'earthquakes', 'Türkiye', 'TurkiyeQu...         1.0   
2       ['Turkey', 'earthquake', 'turkeyearthquake2023...         0.0   
3         ['turkeyearthquake2023', 'earthquake', 'Syria']         0.0   
4       ['turkey', 'earthquake', 'turkiye', 'india', '...         0.0   
...                                                   ...         ...   
478047  ['immigrant', 'germany', 'turkey', 'internatio...         0.0   
478048               ['Earthquake', 'terremoto', 'Spain']         4.0   
478049         ['Earthquake', 'sismo', 'Calama', 'Chile']         3.0   
478050  ['ottomanempire', 'ottoman', 'osman', 'osmanbe...         0.0   
478051             ['Arabs', 'Kurds', 'Yazidis', 'Syria']         2.0   

        rt_count  followers_count isVerified language coordinates place  \
0            0.0       19727712.0       True       hi         NaN   NaN   
1            0.0           5697.0       True       en         NaN   NaN   
2            0.0              1.0      False       en         NaN   NaN   
3            0.0              3.0      False       en         NaN   NaN   
4            0.0             17.0      False      und         NaN   NaN   
...          ...              ...        ...      ...         ...   ...   
478047       0.0           1362.0      False       en         NaN   NaN   
478048       2.0          44544.0      False       es         NaN   NaN   
478049       2.0          44544.0      False       en         NaN   NaN   
478050       0.0             66.0      False       en         NaN   NaN   
478051       1.0           3891.0      False       en         NaN   NaN   

                      source  
0       Twitter Media Studio  
1            Twitter Web App  
2        Twitter for Android  
3        Twitter for Android  
4        Twitter for Android  
...                      ...  
478047             eClincher  
478048             emsc-csem  
478049             emsc-csem  
478050   Twitter for Android  
478051       Twitter Web App  

[478052 rows x 11 columns]

# Selecting Only Concerned Columns

In [205]:
df=df[['hashtags','like_count','rt_count']]
df

hashtags  like_count  \
0       ['ATDigital', 'Turkey', 'Earthquake', 'TurkeyE...         0.0   
1       ['Hatay', 'earthquakes', 'Türkiye', 'TurkiyeQu...         1.0   
2       ['Turkey', 'earthquake', 'turkeyearthquake2023...         0.0   
3         ['turkeyearthquake2023', 'earthquake', 'Syria']         0.0   
4       ['turkey', 'earthquake', 'turkiye', 'india', '...         0.0   
...                                                   ...         ...   
478047  ['immigrant', 'germany', 'turkey', 'internatio...         0.0   
478048               ['Earthquake', 'terremoto', 'Spain']         4.0   
478049         ['Earthquake', 'sismo', 'Calama', 'Chile']         3.0   
478050  ['ottomanempire', 'ottoman', 'osman', 'osmanbe...         0.0   
478051             ['Arabs', 'Kurds', 'Yazidis', 'Syria']         2.0   

        rt_count  
0            0.0  
1            0.0  
2            0.0  
3            0.0  
4            0.0  
...          ...  
478047       0.0  
478048       2.0  
478049       2.0  
478050       0.0  
478051       1.0  

[478052 rows x 3 columns]

In [206]:
#Combining words in a single phrase
def unlisting(*x):
    g=''
    a=str(list(x))
    b=a.replace('[','')
    c=b.replace(']','')
    d=c.replace('"','')
    e=d.replace('\'','')
    f=e.split(',')
    for i in f:
        g+=str(i)
       
    return g
df['hashtags1']=df['hashtags'].apply(unlisting)
df

C:\Users\User\AppData\Local\Temp\ipykernel_13032\2655631405.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['hashtags1']=df['hashtags'].apply(unlisting)


hashtags  like_count  \
0       ['ATDigital', 'Turkey', 'Earthquake', 'TurkeyE...         0.0   
1       ['Hatay', 'earthquakes', 'Türkiye', 'TurkiyeQu...         1.0   
2       ['Turkey', 'earthquake', 'turkeyearthquake2023...         0.0   
3         ['turkeyearthquake2023', 'earthquake', 'Syria']         0.0   
4       ['turkey', 'earthquake', 'turkiye', 'india', '...         0.0   
...                                                   ...         ...   
478047  ['immigrant', 'germany', 'turkey', 'internatio...         0.0   
478048               ['Earthquake', 'terremoto', 'Spain']         4.0   
478049         ['Earthquake', 'sismo', 'Calama', 'Chile']         3.0   
478050  ['ottomanempire', 'ottoman', 'osman', 'osmanbe...         0.0   
478051             ['Arabs', 'Kurds', 'Yazidis', 'Syria']         2.0   

        rt_count                                          hashtags1  
0            0.0       ATDigital Turkey Earthquake TurkeyEarthquake  
1            0.0  Hatay earthquakes Türkiye TurkiyeQuakes Turkey...  
2            0.0   Turkey earthquake turkeyearthquake2023 IftiMania  
3            0.0              turkeyearthquake2023 earthquake Syria  
4            0.0  turkey earthquake turkiye india operationdost ...  
...          ...                                                ...  
478047       0.0  immigrant germany turkey international birolba...  
478048       2.0                         Earthquake terremoto Spain  
478049       2.0                      Earthquake sismo Calama Chile  
478050       0.0  ottomanempire ottoman osman osmanbey Turkey Is...  
478051       1.0                          Arabs Kurds Yazidis Syria  

[478052 rows x 4 columns]

# Applying Naive Bayes Algorithm first on column like_count

In [181]:
df1=df[['hashtags1','like_count']]
df1

hashtags1  like_count
0            ATDigital Turkey Earthquake TurkeyEarthquake         0.0
1       Hatay earthquakes Türkiye TurkiyeQuakes Turkey...         1.0
2        Turkey earthquake turkeyearthquake2023 IftiMania         0.0
3                   turkeyearthquake2023 earthquake Syria         0.0
4       turkey earthquake turkiye india operationdost ...         0.0
...                                                   ...         ...
478047  immigrant germany turkey international birolba...         0.0
478048                         Earthquake terremoto Spain         4.0
478049                      Earthquake sismo Calama Chile         3.0
478050  ottomanempire ottoman osman osmanbey Turkey Is...         0.0
478051                          Arabs Kurds Yazidis Syria         2.0

[478052 rows x 2 columns]

In [182]:
#Sampling 20%
df1.like_count.value_counts() *20/100

0.0       37735.2
1.0       18678.8
2.0        9598.0
3.0        5612.4
4.0        3651.8
           ...   
4019.0        0.2
946.0         0.2
1700.0        0.2
827.0         0.2
5217.0        0.2
Name: like_count, Length: 1864, dtype: float64

In [186]:
#Sampling 80%
df1.like_count.value_counts() *80/100

0.0       150940.8
1.0        74715.2
2.0        38392.0
3.0        22449.6
4.0        14607.2
            ...   
4019.0         0.8
946.0          0.8
1700.0         0.8
827.0          0.8
5217.0         0.8
Name: like_count, Length: 1864, dtype: float64

In [187]:
#0-Negative
a=int(150939.2/50)
df1[df1.like_count==0][:a]

hashtags1  like_count
0           ATDigital Turkey Earthquake TurkeyEarthquake         0.0
2       Turkey earthquake turkeyearthquake2023 IftiMania         0.0
3                  turkeyearthquake2023 earthquake Syria         0.0
4      turkey earthquake turkiye india operationdost ...         0.0
5           Earthquake Hatay Turkey turkeyearthquake2023         0.0
...                                                  ...         ...
10133  Syria earthquake death injury crisis TurkeyEar...         0.0
10137  earthquake Turkey Syria OperationDost Ministry...         0.0
10142                   Rohingya earthquake Turkey Syria         0.0
10144                            earthquake turkey Syria         0.0
10157                                  Turkey earthquake         0.0

[3018 rows x 2 columns]

In [188]:
#1-Somewhat Negative
b=int(74715.2/50)
df1[df1.like_count==1][:b]

hashtags1  like_count
1     Hatay earthquakes Türkiye TurkiyeQuakes Turkey...         1.0
6                    Türkiye Syria earthquake Canadians         1.0
13                              earthquake Turkey Syria         1.0
14                  earthquake Turkey disaster recovery         1.0
18               Turkey turkeyearthquake2023 earthquake         1.0
...                                                 ...         ...
8964   people Türkiye Syria earthquake water sanitation         1.0
8967  Feature Earthquake Dubai LetsBrewIt BrewIt The...         1.0
8985                           Syria earthquake Türkiye         1.0
8988   turkey earthquakeinturkey earthquake news rescue         1.0
8994                  Armenia Turkey Margara earthquake         1.0

[1494 rows x 2 columns]

In [189]:
#2-Neutral
c=int(38392.0/50)
df1[df1.like_count==2][:c]

hashtags1  like_count
11    turkeyearthquake2023 earthquake Turkey PrayFor...         2.0
15                        Media PMModi Syria earthquake         2.0
17                 Turkey Earthquake EarthquakeInTurkey         2.0
25    ArianaNews Turkey Earthquake US AntonyBlinken ...         2.0
29                                    earthquake turkey         2.0
...                                                 ...         ...
6743                                  Turkey earthquake         2.0
6765  Syria Türkiye Earthquake Syria SharingIsCaring...         2.0
6766  الزلزال إدلب جنديرس الريحانية منظمة_سداد_الإنس...         2.0
6828             earthquake Turkey Syria RisingTalagang         2.0
6831            hatay samandağ turkey deprem earthquake         2.0

[767 rows x 2 columns]

In [190]:
#3-Somewhat Positive
d=int(22449.6/50)
df1[df1.like_count==3][:d]

hashtags1  like_count
16    TurkiyeQuakes Turkey Syria Earthquake turkeyea...         3.0
58    earthquake Turkey earthquakeinturkey turkeyear...         3.0
78                              earthquake Turkey Syria         3.0
104                            Earthquake Turkiye Syria         3.0
119              Turkey earthquake turkeyearthquake2023         3.0
...                                                 ...         ...
5719  Kazakhstan earthquake Türkiye deprem Turkey ea...         3.0
5732            Turkey Syria earthquake EveryStepCloser         3.0
5740                                  Turkey earthquake         3.0
5757  NDRF Turkey earthquake TurkeySyriaEarthquake20...         3.0
5760                     Syria Cyprus Turkey earthquake         3.0

[448 rows x 2 columns]

In [191]:
#4-Positive
e=int(14607.2/50)
df1[df1.like_count==4][:e]

hashtags1  like_count
28                                    Turkey Earthquake         4.0
34         Turkey Syria earthquake turkeyearthquake2023         4.0
123                            syria earthquake canpoli         4.0
173   earthquake Turquie turkeyearthquake2023 Turkey...         4.0
271                             earthquake Turkey Syria         4.0
...                                                 ...         ...
5447                    Earthquake deprem Göksun Turkey         4.0
5501  earthquake Kahramanmaras Istanbul Turkey Turke...         4.0
5518                earthquake Turkey Syria Iran Tehran         4.0
5549           Turkey cats dogs rescue birds earthquake         4.0
5569               Turkey NDRF Earthquake BharatExpress         4.0

[292 rows x 2 columns]

In [192]:
#testing data
test = pd.concat([df1[df1.like_count==0][:a],df1[df1.like_count==1][:b],df1[df1.like_count==2][:c],
                  df1[df1.like_count==3][:d],df1[df1.like_count==4][:e]])[["hashtags1","like_count"]]
print(len(test))
display(test)

6019


hashtags1  like_count
0          ATDigital Turkey Earthquake TurkeyEarthquake         0.0
2      Turkey earthquake turkeyearthquake2023 IftiMania         0.0
3                 turkeyearthquake2023 earthquake Syria         0.0
4     turkey earthquake turkiye india operationdost ...         0.0
5          Earthquake Hatay Turkey turkeyearthquake2023         0.0
...                                                 ...         ...
5447                    Earthquake deprem Göksun Turkey         4.0
5501  earthquake Kahramanmaras Istanbul Turkey Turke...         4.0
5518                earthquake Turkey Syria Iran Tehran         4.0
5549           Turkey cats dogs rescue birds earthquake         4.0
5569               Turkey NDRF Earthquake BharatExpress         4.0

[6019 rows x 2 columns]

In [193]:
#training data        
a=int(37735.2/50)
b=int(18678.8/50)
c=int(9598.0/50)
d=int(5612.4/50)
e=int(3651.8/50)
p=int(150939.2/20)
q=int(74715.2/20)
r=int(38392.0/20)
s=int(22449.6/20)
t=int(14607.2/20)
v=df1[df1.like_count==0][a:p]
w=df1[df1.like_count==1][b:q]
x=df1[df1.like_count==2][c:r]
y=df1[df1.like_count==3][d:s]
z=df1[df1.like_count==4][e:t]
train = pd.concat([df1[df1.like_count==0][a:p],df1[df1.like_count==1][b:q],df1[df1.like_count==2][c:r],
                    df1[df1.like_count==3][d:s],df1[df1.like_count==4][e:t]])[["hashtags1","like_count"]]
print(len(train))
display(train)

13549


hashtags1  like_count
2239          earthquake Hatay Turkey Aleppo Idlib Syrie         0.0
2243                earthquake BreakingNews Syria Turkey         0.0
2244        Turkey Erdogan earthquake earthquakeinturkey         0.0
2246   Turkey 6_4_magnitude earthquake this_evening_T...         0.0
2247                    earthquake deprem Antioch Turkey         0.0
...                                                  ...         ...
14339                                         Earthquake         4.0
14341                    Earthquake deprem Göksun Turkey         4.0
14399                             p2pquake 地震 earthquake         4.0
14407                                   earthquake Syria         4.0
14410                                  earthquake Sutton         4.0

[13549 rows x 2 columns]

In [194]:
X=train[["hashtags1"]] #corpus all text from your dataset
X

hashtags1
2239          earthquake Hatay Turkey Aleppo Idlib Syrie
2243                earthquake BreakingNews Syria Turkey
2244        Turkey Erdogan earthquake earthquakeinturkey
2246   Turkey 6_4_magnitude earthquake this_evening_T...
2247                    earthquake deprem Antioch Turkey
...                                                  ...
14339                                         Earthquake
14341                    Earthquake deprem Göksun Turkey
14399                             p2pquake 地震 earthquake
14407                                   earthquake Syria
14410                                  earthquake Sutton

[13549 rows x 1 columns]

In [195]:
#Convert corpus into vector with sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
#list of text document
courpus = X.hashtags1.values
# create transorm
vectorizer = TfidfVectorizer()
# tokeniz and build vocab
vectorizer.fit(courpus)
#summarize
print(vectorizer.vocabulary_)

{'earthquake': 2059, 'hatay': 3071, 'turkey': 7392, 'aleppo': 306, 'idlib': 3380, 'syrie': 6907, 'breakingnews': 1056, 'syria': 6846, 'erdogan': 2303, 'earthquakeinturkey': 2081, '6_4_magnitude': 55, 'this_evening_tremors_were_felt': 7159, 'across_the_levant': 134, 'deprem': 1766, 'antioch': 461, 'turkeyearthquake': 7413, 'turkeytravel': 7462, 'turkeysyriaearthquake': 7456, 'زلزال_تركيا_سوريا': 8582, 'تركيا': 8504, 'الولايات_المتحدة': 8478, 'turkeyearthquake2023': 7414, 'israel': 3619, 'lebanon': 4112, 'building': 1100, 'again': 207, 'shakes': 6334, 'லநட': 8813, 'கம': 8795, 'யத': 8807, 'turkiye': 7499, 'amaq': 373, 'أعماق': 8360, 'baitussalam': 708, 'baitussalamcan': 709, 'antakya': 452, 'breaking': 1051, 'uzunbağ': 7764, 'syriaearthquake': 6856, 'turkeysyriaearthquake2023': 7457, 'syrian': 6865, 'earthquakesyria': 2105, 'quake': 5708, 'usgs': 7742, 'siria': 6421, 'vina2023': 7850, 'biden': 879, 'eebaftas': 2157, 'baftas': 698, 'ukraina': 7616, 'loveontourperth': 4242, 'm6_4': 4263, 'd

In [196]:
#Transform Training and Testing input text into vector using above
train_x = vectorizer.transform(train.hashtags1.values).toarray()
train_y = train.like_count.values
test_x = vectorizer.transform(test.hashtags1.values).toarray()
test_y = test.like_count.values
display("Train_x",train_x)
display("Train_y",train_y)
display("Test_x",test_x)
display("Test_y",test_y)
print(len(train_x),len(train_y))
print(len(test_x),len(test_y))

'Train_x'

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

'Train_y'

array([0., 0., 0., ..., 4., 4., 4.])

'Test_x'

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

'Test_y'

array([0., 0., 0., ..., 4., 4., 4.])

13549 13549
6019 6019


In [197]:
#Bernoulli Naive Bayes for Binary Classification
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()
clf.fit(train_x,train_y)

BernoulliNB()

In [198]:
#Now Apply prediction on Unseendata
y_predict = clf.predict(test_x)
y_predict

array([0., 0., 0., ..., 0., 0., 0.])

In [199]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(test_y,y_predict)
cm

array([[2854,  121,   19,   15,    9],
       [1121,  345,   24,    3,    1],
       [ 589,   50,  127,    0,    1],
       [ 357,   25,   52,   14,    0],
       [ 232,   19,   34,    3,    4]], dtype=int64)

In [200]:
accuracy_score(test_y, y_predict)

0.5555740156172122

In [201]:
#sklearn.metrics.classification_report
from sklearn.metrics import classification_report
#                           Actual Unseen data
print(classification_report(test_y,y_predict))

              precision    recall  f1-score   support

         0.0       0.55      0.95      0.70      3018
         1.0       0.62      0.23      0.34      1494
         2.0       0.50      0.17      0.25       767
         3.0       0.40      0.03      0.06       448
         4.0       0.27      0.01      0.03       292

    accuracy                           0.56      6019
   macro avg       0.47      0.28      0.27      6019
weighted avg       0.54      0.56      0.47      6019



# Applying Naive Bayes Algorithm second on column rt_count

In [207]:
df2=df[['hashtags1','rt_count']]
df2

hashtags1  rt_count
0            ATDigital Turkey Earthquake TurkeyEarthquake       0.0
1       Hatay earthquakes Türkiye TurkiyeQuakes Turkey...       0.0
2        Turkey earthquake turkeyearthquake2023 IftiMania       0.0
3                   turkeyearthquake2023 earthquake Syria       0.0
4       turkey earthquake turkiye india operationdost ...       0.0
...                                                   ...       ...
478047  immigrant germany turkey international birolba...       0.0
478048                         Earthquake terremoto Spain       2.0
478049                      Earthquake sismo Calama Chile       2.0
478050  ottomanempire ottoman osman osmanbey Turkey Is...       0.0
478051                          Arabs Kurds Yazidis Syria       1.0

[478052 rows x 2 columns]

In [208]:
#Sampling 20%
df2.rt_count.value_counts() *20/100

0.0        55536.8
1.0        14586.4
2.0         6483.4
3.0         3725.2
4.0         2381.6
            ...   
540.0          0.2
2221.0         0.2
13712.0        0.2
1312.0         0.2
3645.0         0.2
Name: rt_count, Length: 1049, dtype: float64

In [209]:
#Sampling 80%
df2.rt_count.value_counts() *80/100

0.0        222147.2
1.0         58345.6
2.0         25933.6
3.0         14900.8
4.0          9526.4
             ...   
540.0           0.8
2221.0          0.8
13712.0         0.8
1312.0          0.8
3645.0          0.8
Name: rt_count, Length: 1049, dtype: float64

In [211]:
#0-Negative
a=int(150939.2/50)
df2[df2.rt_count==0][:a]

hashtags1  rt_count
0          ATDigital Turkey Earthquake TurkeyEarthquake       0.0
1     Hatay earthquakes Türkiye TurkiyeQuakes Turkey...       0.0
2      Turkey earthquake turkeyearthquake2023 IftiMania       0.0
3                 turkeyearthquake2023 earthquake Syria       0.0
4     turkey earthquake turkiye india operationdost ...       0.0
...                                                 ...       ...
5987  delusion AllahuAkbar earthquake turkey turkeye...       0.0
5990                                  earthquake Turkey       0.0
5991                    earthquake turkey Syria Turkiye       0.0
5992  UN ООН Turkiye Syria earthquake humanitarianai...       0.0
5994    earthquake Syria SyrianNationalEarthquakeCenter       0.0

[3018 rows x 2 columns]

In [213]:
#1-Somewhat Negative
b=int(74715.2/50)
df2[df2.rt_count==1][:b]

hashtags1  rt_count
15                        Media PMModi Syria earthquake       1.0
17                 Turkey Earthquake EarthquakeInTurkey       1.0
23    JUSTIN turkeyearthquake2023 syriaearthquake Tu...       1.0
28                                    Turkey Earthquake       1.0
29                                    earthquake turkey       1.0
...                                                 ...       ...
7296                     Earthquake deprem Afşin Turkey       1.0
7301                            earthquake Turkey Syria       1.0
7305  سانا اللاذقية StopSanctionsOnSyrians SSOS SYRI...       1.0
7306           rescue earthquake hatay turkey KameraOne       1.0
7308  سعودية سورية StopSanctionsOnSyrians SSOS SYRIA...       1.0

[1494 rows x 2 columns]

In [214]:
#2-Neutral
c=int(38392.0/50)
df2[df2.rt_count==2][:c]

hashtags1  rt_count
16    TurkiyeQuakes Turkey Syria Earthquake turkeyea...       2.0
19         Turkey Syria Earthquake turkeyearthquake2023       2.0
37                 NewsInPhoto earthquake Türkiye Syria       2.0
90                    Earthquake deprem Elbistan Turkey       2.0
93                    Earthquake deprem Elbistan Turkey       2.0
...                                                 ...       ...
9426  Adıyaman Anatolia Turchia terremoto Turkey ear...       2.0
9437                                  earthquake Turkey       2.0
9450  BREAKING Turkiye Turkey news earthquake Russia...       2.0
9462  Erdogan TurkeyEarthquake Turkey Turkiye Türkiy...       2.0
9465  Levanten_sanciones_contra_Siria Siria terremot...       2.0

[767 rows x 2 columns]

In [215]:
#3-Somewhat Positive
d=int(22449.6/50)
df2[df2.rt_count==3][:d]

hashtags1  rt_count
66                       Turkey Biden Ukraine earthquake       3.0
74                    NewsTakHeadlines Turkey Earthquake       3.0
122    Turkey Pakistan earthquake turkeyearthquake202...       3.0
214                   Earthquake deprem Yayladağı Turkey       3.0
226                              Turkey earthquake Syria       3.0
...                                                  ...       ...
10336  səfirlik türkiyə photo stock Azerbaijan Baku p...       3.0
10338     earthquake HTS Jindires Afrin Syria SNA Turkey       3.0
10420  Zhejiang rescue Turkey China earthquake miracl...       3.0
10430  SidraSaddamShah TurkeyQuake Syria_earthquake T...       3.0
10433              earthquake Turkey Syria scammers scam       3.0

[448 rows x 2 columns]

In [216]:
#4-Positive
e=int(14607.2/50)
df2[df2.rt_count==4][:e]

hashtags1  rt_count
161                 TurkeyEarthquake Earthquake Syria US       4.0
253    earthquake Turkey impact turkeyearthquake2023 ...       4.0
336                      Turkey earthquake Turquia sismo       4.0
355                     Earthquake deprem Antioch Turkey       4.0
439    σεισμος_συρια σεισμος_Τουρκια earthquake Turke...       4.0
...                                                  ...       ...
10702                earthquake Turkiye Syria earthquake       4.0
10710                            Turkey Syria Earthquake       4.0
10722  Earthquake Syria Turkey Quake SyriaTurkeyEarth...       4.0
10725  Rescue TurkeyEarthquake RescueTeams BlackDay T...       4.0
10729              Kahramanmaras Turkey Syria Earthquake       4.0

[292 rows x 2 columns]

In [217]:
#testing data
test = pd.concat([df2[df2.rt_count==0][:a],df2[df2.rt_count==1][:b],df2[df2.rt_count==2][:c],
                  df2[df2.rt_count==3][:d],df2[df2.rt_count==4][:e]])[["hashtags1","rt_count"]]
print(len(test))
display(test)

6019


hashtags1  rt_count
0           ATDigital Turkey Earthquake TurkeyEarthquake       0.0
1      Hatay earthquakes Türkiye TurkiyeQuakes Turkey...       0.0
2       Turkey earthquake turkeyearthquake2023 IftiMania       0.0
3                  turkeyearthquake2023 earthquake Syria       0.0
4      turkey earthquake turkiye india operationdost ...       0.0
...                                                  ...       ...
10702                earthquake Turkiye Syria earthquake       4.0
10710                            Turkey Syria Earthquake       4.0
10722  Earthquake Syria Turkey Quake SyriaTurkeyEarth...       4.0
10725  Rescue TurkeyEarthquake RescueTeams BlackDay T...       4.0
10729              Kahramanmaras Turkey Syria Earthquake       4.0

[6019 rows x 2 columns]

In [218]:
#training data        
a=int(37735.2/50)
b=int(18678.8/50)
c=int(9598.0/50)
d=int(5612.4/50)
e=int(3651.8/50)
p=int(150939.2/20)
q=int(74715.2/20)
r=int(38392.0/20)
s=int(22449.6/20)
t=int(14607.2/20)
v=df2[df2.rt_count==0][a:p]
w=df2[df2.rt_count==1][b:q]
x=df2[df2.rt_count==2][c:r]
y=df2[df2.rt_count==3][d:s]
z=df2[df2.rt_count==4][e:t]
train = pd.concat([df2[df2.rt_count==0][a:p],df2[df2.rt_count==1][b:q],df2[df2.rt_count==2][c:r],
                    df2[df2.rt_count==3][d:s],df2[df2.rt_count==4][e:t]])[["hashtags1","rt_count"]]
print(len(train))
display(train)

13549


hashtags1  rt_count
1370                    BREAKING Hatay Turkey earthquake       0.0
1371                       Turkey earthquake Hatay Syria       0.0
1373                    earthquake deprem Antioch Turkey       0.0
1375                            earthquake Turkey Syrian       0.0
1379             Turkey earthquake EarthquakeTurkeySyria       0.0
...                                                  ...       ...
30676  tanka poetry poem Earthquake Earthquakes Turke...       4.0
30783                                       Turkey Syria       4.0
30785  voadari voasocial voaafghanistan turkey rubble...       4.0
30976                                              Syria       4.0
31007                                         Earthquake       4.0

[13549 rows x 2 columns]

In [219]:
X=train[["hashtags1"]] #corpus all text from your dataset
X

hashtags1
1370                    BREAKING Hatay Turkey earthquake
1371                       Turkey earthquake Hatay Syria
1373                    earthquake deprem Antioch Turkey
1375                            earthquake Turkey Syrian
1379             Turkey earthquake EarthquakeTurkeySyria
...                                                  ...
30676  tanka poetry poem Earthquake Earthquakes Turke...
30783                                       Turkey Syria
30785  voadari voasocial voaafghanistan turkey rubble...
30976                                              Syria
31007                                         Earthquake

[13549 rows x 1 columns]

In [220]:
#Convert corpus into vector with sklearn
from sklearn.feature_extraction.text import TfidfVectorizer
#list of text document
courpus = X.hashtags1.values
# create transorm
vectorizer = TfidfVectorizer()
# tokeniz and build vocab
vectorizer.fit(courpus)
#summarize
print(vectorizer.vocabulary_)

{'breaking': 938, 'hatay': 2738, 'turkey': 6745, 'earthquake': 1846, 'syria': 6239, 'deprem': 1585, 'antioch': 408, 'syrian': 6261, 'earthquaketurkeysyria': 1891, 'mynewsgh': 4271, 'ktkammond': 3592, 'case5': 1098, 'minority': 4123, 'rescue': 5354, 'turkeyearthquake2023': 6763, 'turkeyearthquake': 6762, 'turkeyquake': 6795, 'lebanon': 3702, 'staysafe': 6076, 'syria_turkey_earthquake': 6243, 'زلزال_تركيا_سوريا': 7863, 'depremoldu': 1608, 'donate': 1760, 'terremoto': 6437, 'تركيا': 7785, 'سوريا': 7887, 'زلزال': 7859, 'turkish': 6819, 'destruction': 1634, 'victims': 7147, 'seismologists': 5727, 'scientists': 5681, 'world': 7339, 'news': 4409, 'ecologytoday': 1916, 'turkeysyriaearthquake': 6804, 'depremani': 1591, 'sondakika': 5978, 'hataydeprem': 2747, 'லநட': 8130, 'கம': 8112, 'المشهد': 7744, 'هزه_ارضيه': 8036, 'زلزال_تركيا': 7862, 'earthquakes': 1880, 'syriaearthquake': 6250, 'richterscale': 5411, 'ahora': 195, 'حلب': 7819, 'ameen': 333, 'sondaki': 5977, 'ka': 3400, 'tsunami': 6699, 'ukr

In [222]:
#Transform Training and Testing input text into vector using above
train_x = vectorizer.transform(train.hashtags1.values).toarray()
train_y = train.rt_count.values
test_x = vectorizer.transform(test.hashtags1.values).toarray()
test_y = test.rt_count.values
display("Train_x",train_x)
display("Train_y",train_y)
display("Test_x",test_x)
display("Test_y",test_y)
print(len(train_x),len(train_y))
print(len(test_x),len(test_y))

'Train_x'

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

'Train_y'

array([0., 0., 0., ..., 4., 4., 4.])

'Test_x'

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

'Test_y'

array([0., 0., 0., ..., 4., 4., 4.])

13549 13549
6019 6019


In [223]:
#Bernoulli Naive Bayes for Binary Classification
from sklearn.naive_bayes import BernoulliNB
clf = BernoulliNB()
clf.fit(train_x,train_y)

BernoulliNB()

In [224]:
#Now Apply prediction on Unseendata
y_predict = clf.predict(test_x)
y_predict

array([0., 0., 0., ..., 0., 0., 0.])

In [225]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

cm = confusion_matrix(test_y,y_predict)
cm

array([[2856,  130,   10,   13,    9],
       [ 934,  552,    5,    2,    1],
       [ 510,  214,   42,    0,    1],
       [ 367,   65,    5,   11,    0],
       [ 227,   44,    5,    0,   16]], dtype=int64)

In [226]:
accuracy_score(test_y, y_predict)

0.5776707094201695

In [227]:
#sklearn.metrics.classification_report
from sklearn.metrics import classification_report
#                           Actual Unseen data
print(classification_report(test_y,y_predict))

              precision    recall  f1-score   support

         0.0       0.58      0.95      0.72      3018
         1.0       0.55      0.37      0.44      1494
         2.0       0.63      0.05      0.10       767
         3.0       0.42      0.02      0.05       448
         4.0       0.59      0.05      0.10       292

    accuracy                           0.58      6019
   macro avg       0.56      0.29      0.28      6019
weighted avg       0.57      0.58      0.49      6019

